package main

const (
	ENV_DATABASE_DSN_INFO    = "DATABASE_DSN_INFO"
	ENV_DATABASE_DSN_TRADE   = "DATABASE_DSN_TRADE"
	ENV_TELEGRAM_BOT_TOKEN   = "TELEGRAM_BOT_TOKEN"
	ENV_CLAUDE_API_KEY       = "CLAUDE_API_KEY"
	ENV_EXCHANGE_PRIVATE_KEY = "EXCHANGE_PRIVATE_KEY"
	ENV_EXCHANGE_RPC_URL     = "EXCHANGE_RPC_URL"
	ENV_DEX_KEY              = "DEX_KEY"
	ENV_DEX_SECRET           = "DEX_SECRET"
)

const (
	PROMPT_FILE_ANALYZE  = "prompt_analyze.txt"
	PROMPT_FILE_DECISION = "prompt_decision.txt"
)
